### ISSUE TITLE
Evitar exceção quando datas são inválidas

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#104]
Algumas licitações tem datas inválidas, como `01/01/0001 00h00`. Datas assim devem ser salva como `None`, para evitar perda dos dados.

```
OverflowError
date value out of range
```

![antes-de-cristo](https://user-images.githubusercontent.com/1899950/80361131-b7427a00-8880-11ea-9c28-491688f2e620.png)

Exemplos: 

http://www.feiradesantana.ba.gov.br/seadm/licitacoes_pm.asp?cat=PMFS&dt=09-2015
http://www.feiradesantana.ba.gov.br/seadm/licitacoes_pm.asp?cat=PMFS&dt=07-2015

**Comment by rennerocha** [comment]
01/01/0001 é uma data completamente válida (não para o projeto obviamente, já que Feira de Santana não é tão antiga assim :-) )

Qual a definição de uma data inválida (mínima aceitável para o campo `session_at`) ?

**Comment by anapaulagomes** [comment]
Verdade, @rennerocha :sweat_smile: Acho que uma data pode ser considerada válida partir de 18 de setembro de 1833 (data da emancipação política da cidade). haha
