### ISSUE TITLE
Remover Recent Actions do painel público

### ISSUE THREAD

**Issue by anaschwendler** [DadosAbertosDeFeira/maria-quiteria#115]
Com a implementação do painel público, uma possível melhoria seria remover a aba `Recent Actions`, porque não será necessária, a princípio.

![image](https://user-images.githubusercontent.com/4131432/82030998-7e384100-9699-11ea-8b05-933429e4fcad.png)

**Comment by anapaulagomes** [comment]
Talvez essa modificação precise ser feita no pacote mesmo: https://github.com/cuducos/django-public-admin

**Comment by cuducos** [comment]
> Talvez essa modificação possa ser feita no pacote mesmo: https://github.com/cuducos/django-public-admin

Concordo! Acho que não faz sentido isso aparecer nesse contexto.

Se ajudar, **acho**, no Jarbas só _escondemos_ com `display: none`: [esse template](https://github.com/okfn-brasil/serenata-de-amor/blob/master/jarbas/dashboard/templates/admin/base_site.html) chama o `dashboard.css` que tem o [`display: none`](https://github.com/okfn-brasil/serenata-de-amor/blob/128bd2f85abb7c55dbf9b0152e70e908d316f9e5/jarbas/dashboard/static/dashboard.css#L5-L7)

**Comment by anapaulagomes** [comment]
Para resolver essa issue, podemos contribuir diretamente com o `django-public-admin` https://github.com/cuducos/django-public-admin/issues/19. 🤝

**Comment by anapaulagomes** [comment]
Já foi resolvida no projeto. 🍾
