### ISSUE TITLE
Os registros sem data devem ser mostrados por último

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#120]
Assumindo que as datas são extremamente relevantes para os usuários que consultam os nossos dados, precisamos colocar os registros sem data por último, para evitar algo como:

![last-true](https://user-images.githubusercontent.com/1899950/82345828-039f5680-99f6-11ea-8151-ee7e6763f28a.png)

Atualmente, na página de [diários oficiais](http://www.dadosabertosdefeira.com.br/painel/datasets/gazette/) os diários sem data são exibidos primeiro, ao invés dos mais recentes.

O modelo de diários já tem um parâmetro para resolver esse problema mas não funciona:

https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/c8ca99198cf084938c71a2b7ae62b7816cfca4a9/datasets/models.py#L243

Esse problema também atinge as [licitações](http://www.dadosabertosdefeira.com.br/painel/datasets/cityhallbid/) - talvez devamos extender a solução para esse problema como padrão a todos os modelos.

**Comment by RaulBSantos** [comment]
Vou trabalhar nesse, Ana :)

**Comment by RaulBSantos** [comment]
Esta configuração no model Gazette está funcionando corretamente com o `nulls_last=True`, testando via terminal fica ok. Porém no painel, a ordenação é sobrescrita por este outro ModelAdmin: 

> https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/e28b35e836c43c21507861bf9a0648419a27d689/datasets/admin.py#L21-L22

Podemos então ou remover esta ordenação no ModelAdmin, para a ordenção no model ser aplicada, ou alterar a ordenação apenas no ModelAdmin para evitar redundância. 

O que vocês acham fazer mais sentido?

Outro ponto que acho legal vermos é se não tem consultas e ordenações rolando sem necessidade.

**Comment by anapaulagomes** [comment]
Boa, @RaulBSantos! Excelente descoberta. Por mim pode remover sim. Acho que deixar a ordenação no model faz sentido.

> Outro ponto que acho legal vermos é se não tem consultas e ordenações rolando sem necessidade.

Bem importante mesmo. O painel está com algumas consultas lentas, verificar isso seria muito útil. Eu tô com uma branch tentando resolver isso mas apenas adicionando uns índices. Se puder verificar isso seria show!
