### ISSUE TITLE
Atualizar site com novo design

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#148]
Enquanto não temos o design do nosso portal, podemos dar um tapa no visual com o redesign da marca feito pela Nataly. Na parte azul, devemos adicionar a imagem de fundo azul também com o nome do projeto e remover o ícone antigo do canto superior esquerdo.

![Group 328](https://user-images.githubusercontent.com/1899950/84647082-4411c780-af03-11ea-9bd4-d3fa81b4ca0e.png)

A alteração deve ser feita em [home/templates/home/index.html](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/master/home/templates/home/index.html).

**Comment by anapaulagomes** [comment]
@ellalves, se tiver qualquer dúvida, manda pra gente!

**Comment by ellalves** [comment]
Adicionei a imagem como fundo da section: 
`
    <section class="hero is-info is-medium is-bold" style="background-image: url('{% static "home/imagem-apresentacao-dadosdefeira.png" %}'); background-size:100%; background-repeat: no-repeat; background-position: center; background-origin: padding-box;">
`
Ocultei o logo e o texto com 'display: none', aqui:

`
                        <a class="navbar-item" href="../" style="display:none">
`
E aqui: 

`
<div class="container has-text-centered" style="display:none">
`
