### ISSUE TITLE
Otimizar busca no painel

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#153]
Muitos models foram criados sem índices (:see_no_evil:) e por isso a busca no painel pode ser lenta em alguns casos.
Precisamos otimizar essa busca no painel para entregar uma resposta rápida aos usuários e também fazer melhor uso dos nossos recursos.

**Comment by RaulBSantos** [comment]
@anapaulagomes , tem algum dump da base oficial ou uma forma fácil de gerar múltiplos registros para testes como esse?

Estou pensando em fazer um comando pra ser usado em devel pra superpopular o banco, acha viável?

**Comment by anapaulagomes** [comment]
@RaulBSantos, eu posso te passar uma cópia do nosso banco em produção, sem problemas. Te mando no Telegram daqui a pouco.
