### ISSUE TITLE
Tipos dos dados retornados

### ISSUE THREAD

**Issue by Jkasnese** [DadosAbertosDeFeira/maria-quiteria#154]
Existe uma coluna nos dados das despesas do COVID chamada _process_num_, número do processo. Os valores em que há o número são type str. Os valores que não há o número são NaN, type float.

Facilitaria se fossem do mesmo tipo. Talvez o crawler pudesse checar e/ou padronizar os tipos por coluna. Nesses casos de ausência, colocar None por exemplo.

**Comment by anapaulagomes** [comment]
@Jkasnese, acho que o problema deve estar na forma como os dados são lidos. Em Python não temos `NaN` e o `None` não é um tipo primitivo. O _spider_ salva um arquivo `.csv`. Aqui um exemplo de como os dados ficam:

```
action,company_or_person,crawled_at,crawled_from,date,document,function,group,number,phase,process_number,published_at,resource,subfunction,summary,type_of_process,value
2291 - Enfrentamento da Emergencia Coronavirus COVID-19,SANTA CASA DE MISERICORDIA FSA,2020-06-15 09:14:46.823960,http://www.transparencia.feiradesantana.ba.gov.br/index.php?view=despesascovid,11/06/2020,13.227.038/0001-43,10 - SAUDE,335043000000000000 - Subvencoes Sociais,20001969,EMPENHO,,11/06/2020,0014 - TRANSF. REC. SUS,122 - ADMINISTRACAO GERAL,"CONVENIO DE COOPERACAO TECNICO FINANCEIRA P/ EXECUCAO DAS ACOES DESCRITAS NA LEI 13.995/2020,REGULAMENTADA ATRAVES DAS PORTARIAS DO MINISTERIO DA SAUDE N1.448/2020 P/ ATENDER AS NECESSIDADES DA ST. CASA DE MISERICORDIA DE FEIRA DE SANTANA. EMENDA PARLAMENTAR 12-2020-11S",Isento,"R$  2.884.587,56"
```

Nesse exemplo o `process_number` não existe mas ele está vazio, em sua posição. O tipo em que ele será transformado depende de como a leitura desse arquivo será feita. Vou fechar essa _issue_ por entender que não temos um problema a ser resolvido no código do projeto.
