### ISSUE TITLE
Adicionar páginas para mais informações sobre o projeto

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#155]
Enquanto nosso design não fica pronto, precisamos dar mais informações as pessoas sobre o que fazemos. Na barra superior, onde temos as nossas redes, teríamos:

* Quem Somos (página para explicar o projeto, o que fazemos, links para as redes)
* Pedidos & Dados (página para listar os pedidos de informação e dados já coletados)
* COVID-19 em Feira
* Blog (link para o Medium)

Atualmente usamos o template [Hero](https://bulmatemplates.github.io/bulma-templates/templates/hero.html). Essas páginas ficariam como no template:

![barra-superior](https://user-images.githubusercontent.com/1899950/85551242-170b9600-b622-11ea-827b-e1d01211fd35.png)

**Comment by di3goleite** [comment]
Olá @anapaulagomes . Vou trabalhar nessa task!

**Comment by RaulBSantos** [comment]
Na parte do Quem somos, temos já o nosso [manifesto](https://medium.com/@dadosabertosdefeira/manifesto-a9cb9207820d) para ser incluído nessa parte

**Comment by sarahdialmeida** [comment]
Oie! quero dar uma maozinha aqui! :)

**Comment by anapaulagomes** [comment]
A ser feito no portal.
