### ISSUE TITLE
Adicionar número de itens extraídos em uma coleta

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#176]
Atualmente utilizamos o [spidermon](https://spidermon.readthedocs.io/) para verificar o formato dos dados coletados e se houve algum erro. Esse relatório, apesar de informar corretamente a respeito da execução e do erro, traz poucos detalhes.

<img width="377" alt="spidermon-telegram" src="https://user-images.githubusercontent.com/1899950/87844070-b9204600-c88f-11ea-886a-b325ec894084.png">

Devemos adicionar no relatório de execução quantos itens foram coletados em cada _spider_. Dessa forma saberemos quando um _spider_ é executado com sucesso e tem algum tempo sem coletar nenhum item, por exemplo.

Um exemplo disso pode ser encontrado [no Querido Diário](https://github.com/okfn-brasil/querido-diario/blob/e70ec30701f2f5b4feae9487059d35d2535546d2/data_collection/gazette/monitors.py#L33).

**Comment by Urahara** [comment]
Bastaria importar e adicionar o `ItemCountMonitor` no `monitors.py`?  https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/eb5eb5ec67c90123e93946934fa68d15cd62a414/scraper/monitors.py#L4-L11

**Comment by anapaulagomes** [comment]
Pelo o que entendi, esse monitor serve pra verificar o número mínimo de itens para coleta. Com o `ItemCountMonitor` temos que especificar o `SPIDERMON_MIN_ITEMS` (https://spidermon.readthedocs.io/en/latest/monitors.html#spidermon.contrib.scrapy.monitors.ItemCountMonitor). Para esse projeto não faz sentido porque nem sempre temos itens coletados todos os dias. Por exemplo: a Câmara tem sessões 3 vezes por semana. Então não teremos uma ata por dia. O mesmo para licitações, diários oficiais etc.

Acredito que aqui temos que pegar o número de itens coletados nas `STATS` do Scrapy e adicionar no relatório do Spidermon para o Telegram.

**Comment by Urahara** [comment]
Entendi! Daria pra criar um extensão e pegar o `item_scraped_count` e depois jogar pro spidermon.

**Comment by Urahara** [comment]
@anapaulagomes É possível pegar a mensagem que vai ser enviado pro Telegram sem precisar configurar um bot?

**Comment by anapaulagomes** [comment]
É sim, @Urahara. Você precisa configurar a variável de ambiente `SPIDERMON_TELEGRAM_FAKE=True` (se não me engano é padrão no `.env.example`). Ao executar um _spider_ ou o comando `python manage.py crawl` a mensagem do Telegram será postada no terminal.

<img width="685" alt="telegram-spidermon" src="https://user-images.githubusercontent.com/1899950/88087561-7eecc800-cb5f-11ea-8eab-b7c09ad26cf7.png">

A mensagem do Telegram é essa embaixo de `FINISHED ACTIONS`.

**Comment by Urahara** [comment]
tks! vou dar uma olhada.

**Comment by anapaulagomes** [comment]
Oi, @Urahara! Você está trabalhando nessa _issue_?
