### ISSUE TITLE
Adicionar __str__ para agenda e lista de presença dos vereadores

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#177]
Dessa forma, podemos ter um título melhor ao clicar na página de registros desses dois modelos (`CityCouncilAgenda` e `CityCouncilAttendanceList`).

Exemplo ao clicar na presença de um vereador:

<img width="531" alt="presenca" src="https://user-images.githubusercontent.com/1899950/87844284-1c12dc80-c892-11ea-816a-c8838a0e709f.png">

Para reproduzir esse bug basta ter registros nos modelos citados e clicar em um deles. A barra deve mostrar informações amigáveis (geralmente já disponível no `__repr__`).

**Comment by KauanAmarante** [comment]
Oi, tudo bem?
Posso puxar essa _issue_ ?

**Comment by anapaulagomes** [comment]
Manda ver, @KauanAmarante! 🚀

**Comment by elicaciocf** [comment]
Kauan, boa noite!

Ainda está trabalhando nessa issue, posso puxar?

**Comment by elicaciocdefarias** [comment]
@anapaulagomes,

Olha como o breadcrumbs do admin aparece

![issue_177_1](https://user-images.githubusercontent.com/15112609/103415215-ef146680-4b5f-11eb-99fb-6bd0e45f0ce4.png)

![issue_177_2](https://user-images.githubusercontent.com/15112609/103415223-f5a2de00-4b5f-11eb-9be6-018d18198964.png)

Não consigo acessar os models, tu pode me ajudar?

**Comment by anapaulagomes** [comment]
Claro! Dá uma olhada na lista de presença no `/painel` (você deve estar no `/admin`, certo?). @elicaciocdefarias

**Comment by elicaciocdefarias** [comment]
@anapaulagomes,

Deu certo!!! Valeu

**Comment by elicaciocdefarias** [comment]
@anapaulagomes,

O que você acha?

![issue_177_3](https://user-images.githubusercontent.com/15112609/103421034-09a70980-4b79-11eb-8a94-12d57d94b33d.png)

![issue_177_4](https://user-images.githubusercontent.com/15112609/103421040-1166ae00-4b79-11eb-9694-064dd4208298.png)

**Comment by anapaulagomes** [comment]
Está ficando ótimo, @elicaciocdefarias! O que acha de ao invés de ter a PK ter a data? Além disso, a Lista de Presença é uma para cada vereador. Talvez seja melhor ter para ela a data e o nome do vereador também.
Tipo "Agenda para 01/10/2020" e "Presença em 01/10/2020 - Fulano de Tal". Acho que assim fica mais humano. Faz sentido?

**Comment by elicaciocdefarias** [comment]
Claro! Faz todo sentido.

**Comment by elicaciocdefarias** [comment]
@anapaulagomes ,

Para o model `CityCouncilAgenda`, acredito que podemos usar o título, já que ele traz a data e o tipo do evento.
ficaria assim: "Agenda para ORDEM DO DIA - 09 DE DEZEMBRO DE 2020", que acha?

**Comment by anapaulagomes** [comment]
Ótimo! Mas confere se todos trazem a data no título. Se sim, manda ver. 👍🏽 @elicaciocdefarias
