### ISSUE TITLE
Adotar "main" como nome para a branch principal ao invés de "master"

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#201]
Eliminar vocabulário racista do nosso dia a dia é um dever de todos os que estão comprometidos com a igualdade, conforme defendido pela constituição brasileira e pelo nosso [código de conduta](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/master/CODE_OF_CONDUCT.md). Assim que grandes pull requests nesse repositório forem mergeados, podemos começar esse movimento.

Referências de outros projetos:

https://github.com/model-bakers/model_bakery/issues/105

**Comment by jroquejr** [comment]
Se master passa a ser main, os PRs em aberto só precisariam ser atualizados, não? Atualizar o destino da mesclagem.
Sempre vai existir um grande pull request entre as mudanças...

**Comment by anapaulagomes** [comment]
Faz sentido! Mas queria esperar um momento mais tranquilo pra isso, pra falar a verdade. 😂

**Comment by anapaulagomes** [comment]
Feito. ✔️ ✊🏽
