### ISSUE TITLE
Criar bot para atualizações do diário oficial

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#203]
Essa issue é o início de um bot no Twitter para atualizações do Diário Oficial de Feira de Santana. Vamos melhorá-lo com o tempo mas, para essa issue, o objetivo é: criar um tweet para cada novo diário oficial. A nossa coleta de dados acontece uma vez por dia e os diários que ainda não estão no banco de dados são salvos. Quando o site está fora, os novos diários serão coletados quando o site voltar (durante a coleta diária às 00:00).

Sugestão de tweet:

> Diário do executivo em 30/09/2020 - Ano VI Edição 1463.
> Link: http://www.diariooficial.feiradesantana.ba.gov.br/atos/executivo/13092P9292020.pdf

Os diários oficiais estão todos nessa [página](http://www.diariooficial.feiradesantana.ba.gov.br/) - tanto os do poder executivo quanto os do legislativo. Temos as informações de poder, ano, edição e link já armazenadas em [Gazette](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/c0f48eb9dc3355789de2f7749dc73e82b8a21595/datasets/models.py#L321).

Requisitos técnicos:

* executar a ação de criar o tweet a partir de uma background task para que seja possível tentar novamente em caso de erros
* para evitar situações onde deu erro mas o tweet foi criado precisamos salvar o id desse tweet no banco e verificar se ele existe antes de tentar criar um tweet

O perfil https://twitter.com/DiarioDeFeira é nosso. Podemos mudar o usuário para seguir um padrão dos bots do projeto também.

Fiquem a vontade para postar qualquer dúvida ou sugestão. Vamos discutir! 🤖

**Comment by jroquejr** [comment]
Eu posso tocar isso.

**Comment by anapaulagomes** [comment]
Será feito em um repositório separado.
