### ISSUE TITLE
Adicionar docker-compose.yml para melhorar experiência de desenvolvimento

### ISSUE THREAD

**Issue by diegofsousa** [DadosAbertosDeFeira/maria-quiteria#216]
Olá pessoal, tudo bem com vocês?

Estive analisando o projeto, desde já parabenizo a todos os contribuidores.

Não sei se isso já foi comentado, mas creio que um arquivo `docker-compose.yml` contendo as imagens do PostgreSQL e RabbitMQ poderia agregar bastante ao projeto, visto que, facilitaria o processo de subir essas instâncias.

O que acham?

**Comment by anapaulagomes** [comment]
Obrigada, @diegofsousa! :) Concordamos! Inclusive temos um PR (em andamento) que dockeriza o projeto. Lá estamos adotando o compose. Como já está em andamento, vou fechar essa issue, certo? Aí tu pode dar uma olhadinha lá e se tiver qualquer dúvida ou sugestão, deixa lá no PR mesmo: #150. Obrigada pela sugestão!

**Comment by diegofsousa** [comment]
Perfeito! Não tinha visto o PR. Obrigado, @anapaulagomes :)
