### ISSUE TITLE
Criar estrutura para API

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#226]
A nossa API será consumida pelo frontend do portal do dados. Essa primeira issue deve ter uma estrutura inicial para a API e um endpoint que será usado como _health check_ (apenas para verificar se está tudo certo com a API).

Por ora, pensamos que o [DRF](https://www.django-rest-framework.org/) é uma boa alternativa, dado que o projeto já utiliza Django e os endpoints não terão lógicas complexas.

Referências para manter em mente:
https://github.com/vintasoftware/python-api-checklist/blob/master/checklist-en.md

**Comment by Augusto94** [comment]
Estou fazendo isso!
