### ISSUE TITLE
Criar endpoint para diários oficiais

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#227]
O endpoint deve servir os dados do model `Gazette`, permitindo busca no conteúdo dos seus arquivos, filtragem por poder, data e ano/edição.

Campos para retornar:
* Fonte (url)
* Data
* Poder (executivo ou legislativo)
* Ano e edição (texto)
* Eventos (texto do model relacionado `GazetteEvent`)

Filtros:
* Texto (busca nos eventos, ano e edição e conteúdo dos arquivos)
* Poder (se executivo, legislativo ou ambos)
* Data (início e fim)

Caso nenhum filtro seja informado, todos os diários devem ser mostrados.

**Comment by soslaio** [comment]
Posso pegar esse issue, que me parece mais difícil que o da autenticação ;-)

**Comment by anapaulagomes** [comment]
😂 Olha, essa aqui é tão importante quanto a autenticação haha Pode sim, @soslaio. Manda ver! Obrigada!

**Comment by soslaio** [comment]
@anapaulagomes o model `GazetteEvent` possui várias informações. Como devem ser feitas as referências à lista de eventos? mostrando informações (como na imagem abaixo) ou apenas com links? Se for como na imagem, quais campos exatamente devem constar?

![image](https://user-images.githubusercontent.com/1789242/104137835-8064b380-537e-11eb-87f1-86c7c98fff63.png)

**Comment by anapaulagomes** [comment]
Oi, @soslaio! Talvez a descrição no PR deve ter passado a mensagem errada mas devemos manter os nomes dos campos originais (não precisamos traduzi-los).

Respondendo tua pergunta: para os eventos podemos ter um campo `events` retornando `title`, `secretariat`, `summary` e `published_on`. Os eventos são raspados e salvos no banco no mesmo momento do diário. Por isso os demais campos serão os mesmos. Pra diminuir o payload, deixaremos os campos repetidos de fora.

**Comment by soslaio** [comment]
Blz, @anapaulagomes, vou separar só esses campos, então.
Sobre a tradução, eu parti do princípio de que qualquer pessoa de fora do projeto deve interagir com pt-br, por isso traduzi os campos. Da mesma forma, a rota que criei foi em pt-br `/diarios`. Deixo tudo em pt-br ou en?

**Comment by anapaulagomes** [comment]
Tentamos manter o código em inglês e a documentação em português. Como os modelos, códigos etc estão em inglês, acredito que faz sentido deixar as rotas em inglês também (seguindo o padrão dos modelos). Obrigada, @soslaio!
