### ISSUE TITLE
Investigar lentidão no pytest durante a coleta dos testes

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#229]
A etapa de coleta dos testes tem feito o processo todo demorar mais que o normal. Essa issue é para investigação do que pode ser feito para melhorar o tempo de coleta e execução dos testes, se possível.

Algumas ideias aqui: https://stackoverflow.com/questions/16417546/how-to-speed-up-pytest

**Comment by anapaulagomes** [comment]
O Ruda resolveu essa _issue_ em tempo recorde. 😅 Na verdade, aparentemente o problema é na minha máquina.

**Comment by rudaporto** [comment]
@anapaulagomes de nada, foi so rodar os tests ;)
