### ISSUE TITLE
Criar endpoint para licitações da prefeitura

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#245]
O endpoint deve servir os dados do model `CityHallBid`.

Campos para retornar:

* Todos, incluindo os campos dos eventos (`CityHallBidEvent`)
* URL do arquivo (`File`)

Filtros:

* Texto (busca na descrição, nos eventos (`CityHallBidEvent`) ~e conteúdo dos arquivos relacionados~
* Data (início e fim)

Caso nenhum filtro seja informado, todos os diários devem ser mostrados.

**Comment by joorgelm** [comment]
Olá,

Fiz um commit no meu fork com o começo dessa implementação: https://github.com/joorgelm/maria-quiteria/commit/80d3fd62ce6153e3d0a2e0286e779f2fb10cea7b

Caso a tarefa esteja livre e a minha implementação no caminho certo, gostaria de contribuir :smile:

**Comment by anapaulagomes** [comment]
Opa! Seja bem-vindo @joorgelm. :) Pode pegar essa sim! Diria que está no caminho certo. Só pediria atenção na hora de selecionar objetos que já estão relacionados; pra que a busca aconteça de maneira mais rápida e com menos acessos ao banco, você pode usar o [select-related](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#select-related) (assim você não precisaria do `events__in`, por exemplo). Qualquer dúvida, pode postar no nosso canal #maria-quiteria no Discord.

**Comment by anapaulagomes** [comment]
@joorgelm depois dá uma olhadinha [nesse comentário](https://github.com/DadosAbertosDeFeira/maria-quiteria/issues/246#issuecomment-754485526) sobre a nomenclatura dos filtros (é o mesmo caso dessa issue). Valeu!

**Comment by joorgelm** [comment]
Ola @anapaulagomes, atualizei novamente o endpoint usando prefetch_related para buscar as licitações e os eventos de uma só vez.

O nome dos parâmetros está igual ao comentário citado anteriormente.

https://github.com/joorgelm/maria-quiteria/blob/204a4b0d09c20c6beb7950030868a9400fdfb395/api/views.py

to com dúvida em relação a _busca no conteúdo dos arquivos relacionados_, a busca deve ser feita em uma entidade diferente?

**Comment by anapaulagomes** [comment]
Massa, @joorgelm. Vou revisar quando o PR tiver aberto, tá? Assim fica melhor.

Em relação aos arquivos, eles estão no model `File`. Nele tem os arquivos da licitação e o seu conteúdo (`content`). Para cada arquivo com conteúdo encontrado precisamos retornar a URL do arquivo também (atualizei a issue com essa informação - tinha me esquecido, my bad).

**Comment by joorgelm** [comment]
O endpoint deve retornar apenas a URL do arquivo caso o conteúdo do mêsmo dê match com a busca textual, certo? Fiquei na dúvida se preciso retornar também o conteúdo do arquivo.

**Comment by anapaulagomes** [comment]
Isso, apenas a URL do arquivo. No futuro devemos retornar um pedaço do texto mas para o MVP apenas a URL é o suficiente.

**Comment by Ladeia** [comment]
Ainda precisa de trabalho nesse ticket?

**Comment by anapaulagomes** [comment]
Oi, @Ladeia! Precisa sim. 🙏🏽 Houve um início muito bom em #284 mas estamos com um problema na busca textual (#124). De todo jeito, podemos implementar o endpoint e depois resolver o problema com a busca. Fica a teu critério.
Se topar me avisa que te assigno na issue.

**Comment by Ladeia** [comment]
Pronto, eu topo implementar o endpoint, pelo que vi está pronto/quase pronto no commit do @joorgelm. Vou baixar a branch, testar local para ver se precisa de algum ajuste.

**Comment by anapaulagomes** [comment]
@Ladeia pode deixar a busca no texto dos arquivos e licitações de fora desse PR, se quiser. No https://github.com/DadosAbertosDeFeira/maria-quiteria/pull/369 usamos o django-filter. Talvez seja uma boa também.

**Comment by anapaulagomes** [comment]
Olá, @Ladeia! Precisando de alguma ajuda aqui?

**Comment by Ladeia** [comment]
Mandando um primeiro pr!
