### ISSUE TITLE
Criar endpoint para dados da agenda da Câmara de Vereadores

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#246]
O endpoint deve servir os dados do model `CityCouncilAgenda`.

Campos para retornar:

* Todos

Filtros:

* Descrição
* Data (início e fim)

Caso nenhum filtro seja informado, todos os diários devem ser mostrados.

**Comment by beatrizuezu** [comment]
Gostaria de pegar essa issue :)

**Comment by anapaulagomes** [comment]
Que demais você aqui, @beatrizuezu! :D Bem-vinda!

Então, eu estava olhando melhor aqui e pensando que ao invés de `description` poderíamos usar algo como `query` ou `q` (que são termos mais comuns). O que acha? A busca seria feita no `details` desse model.
Sobre `start_date` e `end_date` faz sentido mesmo.

Caso queira dar uma espiada nos dados, eles estão aqui: http://www.dadosabertosdefeira.com.br/painel/datasets/citycouncilagenda/

**Comment by beatrizuezu** [comment]
> Que demais você aqui, @beatrizuezu! :D Bem-vinda!
> 
> Então, eu estava olhando melhor aqui e pensando que ao invés de `description` poderíamos usar algo como `query` ou `q` (que são termos mais comuns). O que acha? A busca seria feita no `details` desse model.
> Sobre `start_date` e `end_date` faz sentido mesmo.
> 
> Caso queira dar uma espiada nos dados, eles estão aqui: http://www.dadosabertosdefeira.com.br/painel/datasets/citycouncilagenda/

Faz mais sentido sim usar o `query`!
