### ISSUE TITLE
Criar endpoint para ata das sessões da Câmara de Vereadores

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#247]
O endpoint deve servir os dados do model `CityCouncilMinute`.

Campos para retornar:

* Todos
* URL do arquivo

Filtros:

* Texto (título e conteúdo dos arquivos das atas)
* Data (início e fim)

Caso nenhum filtro seja informado, todos as atas devem ser mostradas.

**Comment by andrewsmedina** [comment]
Vou pegar essa issue.

**Comment by anapaulagomes** [comment]
Massa, @andrewsmedina! Adicionei um campo que faltou (a url do arquivo).

**Comment by anapaulagomes** [comment]
Alô, @andrewsmedina! Ainda vai rolar essa contribuição? 🙏🏽

**Comment by andrewsmedina** [comment]
Vai rolar sim. Vou ver se desenrolo isso essa semana

**Comment by andrewsmedina** [comment]
@exageraldo essa semana sai
