### ISSUE TITLE
Adicionar autenticação para acesso a API

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#270]
Devido a limitação de recursos, atualmente a API deve ser acessada apenas pelo nosso frontend (e outras aplicações do projeto).

**Comment by soslaio** [comment]
Vou dar uma olhada nisso.
https://github.com/soslaio/maria-quiteria/tree/autenticacao-jwt

**Comment by anapaulagomes** [comment]
Resolvido na #272!
