### ISSUE TITLE
Criar endpoint para assiduidade de Vereadores

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#276]
O endpoint deve servir os dados do model `CityCouncilAttendanceList`.

Campos para retornar:

* Todos

Filtros:

* Texto (vereador)
* Data (início e fim)
* Situação

Caso nenhum filtro seja informado, todos os dados devem ser mostrados.

**Comment by elicaciocf** [comment]
Olá,

Vou pegar essa.

**Comment by elicaciocdefarias** [comment]
Olá,

Vou pegar essa.

**Comment by anapaulagomes** [comment]
Show! 😍 @elicaciocdefarias

**Comment by elicaciocdefarias** [comment]
Ana,

Peguei emprestadas as dicas da issue #277 e alterei o nome dos filtros.

Antes:

- Texto (vereador)
- Data (início e fim)
- Situação

Agora:

- query
- start_date
- end_date
- status

Faz sentido?

**Comment by anapaulagomes** [comment]
Perfeito, @elicaciocdefarias! 👍🏽
