### ISSUE TITLE
Adicionar documentação "ao vivo" para API

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#278]
Para facilitar o trabalho das pessoas desenvolvedoras é bom ter uma documentação _live_ para testar a API, ver os parâmetros etc. Referência: https://www.django-rest-framework.org/topics/documenting-your-api/

Para a autenticação, temos a página no [Wiki](https://github.com/DadosAbertosDeFeira/maria-quiteria/wiki/API) explicando passo a passo. A documentação dos endpoints poderia estar lá também mas ficaria extensa demais a partir de poucos endpoints.

**Comment by soslaio** [comment]
Posso pegar essa.

**Comment by anapaulagomes** [comment]
Oi, @soslaio! Eu de novo. 😇 Estamos pra começar o projeto do bot do diário oficial e vamos ter pessoas que nunca contribuiram para open source e nem esse projeto utilizando a API. Ainda vai rolar contribuir com essa issue?

**Comment by exageraldo** [comment]
A gente tava dando uma olhada na [drf-yasg](https://github.com/axnsan12/drf-yasg/) e pareceu bem legal e tranquilo de usar.

**Comment by luandadantas** [comment]
Curti essa task! Mas vou finalizar algumas outras que já tenho no Diário de Feira, se quando finalizar lá, essa ainda tiver aberta, pego ela :D

**Comment by luan-gomes** [comment]
Alguém trabalhando nesta task? Gostaria de pegar ela para começar ;)

**Comment by anapaulagomes** [comment]
Joga duro, @luan-gomes!

**Comment by anapaulagomes** [comment]
Oi @luan-gomes! Precisando de ajuda por aqui? :) Posso ajudar!

**Comment by sheory** [comment]
Comecando essa
