### ISSUE TITLE
Salvar pedidos de informação

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#304]
Atualmente fazemos pedidos de informação e salvamos em uma planilha. Nessa planilha temos alguns dados sensíveis que podem levar a acesso de informações como CPF e endereço dos criadores do pedido. Além disso, é difícil de visualizar nela em qual etapa os pedidos estão. Por isso, devemos salvar no banco os pedidos de informação, seus estados e quando foram modificados e denúncias originadas a partir dele.

Precisamos salvar todas as informações dos pedidos e só exibir no nosso painel o que pode ser público, preservando as informações pessoais de quem criou mas dando visibilidade sobre qual pedido foi feito, a qual órgão e quando.

É importante saber quando o pedido mudou de estado (de "em andamento" para "respondido" etc) para futuramente termos estatísticas do tempo de resposta.

**Comment by guilhermelowa** [comment]
Muito massa! Como a gente pode saber quando o pedido mudou de estado? Seria fazer o pedido pelo Dados Abertos e acompanhar o email?

**Comment by anapaulagomes** [comment]
Por enquanto não vamos fazer os pedidos pela plataforma, só visualizar o que é feito por nós e dar visibilidade. Mas quem quiser acompanhar poderá consultar a página mesmo.

**Comment by anapaulagomes** [comment]
Será feito em um projeto a parte. https://github.com/dadosAbertosDeFeira/pedidos
