### ISSUE TITLE
Checar arquivos se arquivos criados estão sendo deletados 

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#305]
Para extrair o conteúdo dos arquivos nós baixamos o arquivo do nosso S3 e passamos para o Tika. Não precisávamos nos preocupar com o espaço porque no Heroku não havia persistência de dados mas agora que estamos na Absam precisamos verificar se esses arquivos estão ficando lá. Se sim, precisamos deletar os arquivos assim que tivermos certeza que o conteúdo foi extraído. Seria bom verificar também se o arquivo já existe em disco antes de tentar baixar do S3.

**Comment by jroquejr** [comment]
@anapaulagomes , em que momento o arquivo é passado para o Tika? Passa apenas a referência e quando terminar de usar ele deveria ser eliminado, é isso?

O [NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) não resolveria? Ele desaparece quando o arquivo é "fechado".

**Comment by anapaulagomes** [comment]
É [aqui](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/184c8997906ba3f05958f0367a06c7d3d9bccb7b/web/datasets/tasks.py#L56). Quando fui buscar lá vi que tem um `unlink` que deleta o arquivo, então questão resolvida. Mas essa ideia é muito boa. Não conhecia. :)
