### ISSUE TITLE
Notificar resultado de acesso a API da Câmara no Telegram

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#368]
Atualmente temos um canal no Telegram para notificação dos itens raspados. Isso é possível graças ao suporte do Scrapy a essas notificações pós execução dos spiders. Seria ótimo ter a mesma notificação após coletar os dados da Câmara (o que é feito acessando a API).

Exemplo da notificação no Telegram:

![Screenshot from 2021-07-04 11-49-31](https://user-images.githubusercontent.com/1899950/124380658-26ee9900-dcbe-11eb-85f9-636bab60e120.png)

**Comment by exageraldo** [comment]
@anapaulagomes cê poderia dar mais contexto sobre onde a gente poderia tá colocando essa notificação?

Tem uma biblioteca que acho bem legal/interessante pra mandar notificações, que é a `notifiers`:
```python
>>> from notifiers import get_notifier
>>> telegram = get_notifier('telegram')
>>> telegram.notify(message='Hi!', token='TOKEN', chat_id=1234)
```
https://github.com/liiight/notifiers
https://notifiers.readthedocs.io/en/latest/providers/telegram.html

Daí onde for necessário mandar notificações, é só usar.

Caso um dia a gente precise de algumas notificações a partir de logs, acho o [`loguru`](https://github.com/Delgan/loguru) bem legal!

**Comment by gomex** [comment]
@anapaulagomes Uma saída assim é o suficiente ou vc quer algo mais tratado?
![image](https://user-images.githubusercontent.com/95132/137239359-0d5beffa-2935-43a3-b60c-8b2741a6b6d5.png)
