### ISSUE TITLE
Problema de "BlacklistedToken" ao tentar acessar a rota "/api/token/verify/"

### ISSUE THREAD

**Issue by exageraldo** [DadosAbertosDeFeira/maria-quiteria#393]
Olá!

Estou tendo o seguinte problema quando tento acessar a rota para verificar o token:
`AttributeError: type object 'BlacklistedToken' has no attribute 'objects'`

Print do erro:
![image](https://user-images.githubusercontent.com/6025018/132787189-9b960a44-9452-4089-8d56-d99f8b7135f2.png)

Dando uma olhada, percebi que pode ser um problema com uma das dependencias do projeto, o [`djangorestframework-simplejwt`](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/main/requirements.txt#L11) e existe uma [issue aberta sobre esse problema](https://github.com/jazzband/djangorestframework-simplejwt/issues/449).

Eu consegui resolver o problema adicionando um item à variavel [`SIMPLE_JWT`](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/main/web/settings.py#L144), ficando:
```python
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=ACCESS_TOKEN_LIFETIME_IN_MINUTES),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=REFRESH_TOKEN_LIFETIME_IN_MINUTES),
    "BLACKLIST_AFTER_ROTATION": False,
}
```

Mas não tenho certeza se mais alguém está enfrentando o mesmo problema.

Pelo que entendi, isso será corrigido na próxima versão da biblioteca, porem não sei quando acontecerá (a issue tem 22 dias e a nova versão não foi lançada até o momento).

**Comment by anapaulagomes** [comment]
Tranquilo. Se der manda um PR pra gente com essa modificação? 🙏🏽

**Comment by exageraldo** [comment]
Feito!
