### ISSUE TITLE
Depois de tornar os links de arquivos públicos não é possível fazer download ou upload via código

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#395]
Mudamos as configurações do nosso bucket no S3 para deixar os links para os arquivos públicos. Assim, caso o link oficial não esteja disponível o cidadão poderá baixar o nosso arquivo de backup.
Porém, depois dessa modificação não conseguimos mais fazer o upload (backup) do arquivo no S3 e nem baixá-lo para extração do conteúdo via código. Precisamos corrigir as permissões e configurações para que seja possível acessar os links publicamente mas também efetuar operações de upload/download com credenciais via código.

**Comment by anapaulagomes** [comment]
No momento estamos usando a variável de ambiente `ENABLE_SIGNAL_FOR_FILE_TASKS` para evitar que tentativas sejam feitas. Para habilitá-la, basta setar o valor 1. Para configurar o acesso ao S3, basta configurar as seguintes variáveis de ambiente:

```
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_S3_BUCKET=dadosabertosdefeira
AWS_S3_BUCKET_FOLDER=maria-quiteria
AWS_S3_REGION=eu-central-1
```

Feito isso, precisamos chamar uma das background tasks, de backup ou extração de conteúdo. O jeito mais fácil seria utilizar a de backup. Para executar o código precisamos acessar o shell do Django: `make shell`. Caso esteja executando localmente precisa configurar a variável `DJANGO_CONFIGURATION` para `Prod` e ter o docker-compose iniciado.

O código abaixo é o passo a passo para iniciar a task de backup:

```
file = File.objects.filter(s3_url__isnull=True).first()  # pegamos o primeiro arquivo sem backup no S3
from web.datasets.tasks import backup_file
backup_file.delay(file.pk)
```

**Comment by exageraldo** [comment]
@anapaulagomes cê acha que [esse link](https://stackoverflow.com/questions/39051477/the-aws-access-key-id-does-not-exist-in-our-records) pode ajudar?

**Comment by anapaulagomes** [comment]
É o primeiro no na lista de buscas do Google @exageraldo 😂
