### ISSUE TITLE
Adiciona hash do commit ao item coletado

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#41]
Dessa forma será possível trackear qual o status do código no momento em que determinado item foi coletado.

**Comment by anapaulagomes** [comment]
@danielfireman, você tem adicionado o hash no DataJusBr, certo? Tem visto vantagem nesse approach?

**Comment by danielfireman** [comment]
Olá @anapaulagomes! Ainda não vimos vantagem na prática por dois motivos:

1. Ainda não houve uma auditoria ou uma contestação a respeito da corrupção dos dados coletados
1. Ainda tem bastante coisas em fluxo e estamos estabilizando o código, daí o master está sendo o alvo
1. Temos poucos coletores

Mas continuo achando que quando o número de coletores aumentar, o código estabilizar e tiver mais gente de olho, esses commits serão bem necessários. Somado ao commit, também guardamos os arquivos coletados, que foram usados como entrada na consolidação.

**Comment by anapaulagomes** [comment]
Excelente. Obrigada pela resposta, @danielfireman!

**Comment by andressadotpy** [comment]
Olá @anapaulagomes! Gostei dessa issue, mas ainda estou tentando pegar algum contexto, então vou fazer algumas perguntas só para entender melhor essa issue, tudo bem?

- Nessa issue então seria criado um novo field, por exemplo, `hash_commit` em [BaseItem](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/f8063fb3dee2d5f9338089737bfae2b7351ccf06/scraper/items.py#L4), certo?

- Depois disso, adicionariamos uma validação nos validators desse modelo em [validators.py para BaseModel](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/9100f450198b1a9b094e2f00c28bc7c96d0b7028/scraper/validators.py#L13), certo?

- E também atualizar os `parses` que constroem os items e a função [save_bid()](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/c253b75814baec7b302dbde04a6f24d9668facdb/web/datasets/management/commands/_cityhall.py#L7), assim como outros lugares que que constroem um Item e os testes.

Eu estou fazendo sentido? Ou será que me perdi um pouco na análise da issue?

**Comment by andressadotpy** [comment]
Show então, pode me assign pra essa issue @anapaulagomes ? Muito obrigada!!

**Comment by anapaulagomes** [comment]
Com certeza. Obrigada a você! @andressadotpy ❤️
