### ISSUE TITLE
Adotar dateutil no projeto

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#410]
Alguns métodos para parsing e manipulação de datas podem ser substituídos pela biblioteca.

**Comment by exageraldo** [comment]
Pra encontrar as partes responsaveis pelas manipulações, eu fiz uma busca geral no projeto colocando apenas `datetime` e mostrou bastante coisa!

A biblioteca possui uma ótima maneira de transformar strings em datas, por exemplo:
```python
In [3]: from dateutil.parser import parse

In [4]: parse("Sat Oct 11 17:13:46 UTC 2003")
Out[4]: datetime.datetime(2003, 10, 11, 17, 13, 46, tzinfo=tzutc())
```

Link do repositório: https://github.com/dateutil/dateutil

**Comment by allythy** [comment]
Tenho interesse em pegar essa issue para colaborar. Já entrei no grupo do Discord e do Telegram para entender mais sobre o projeto e tirar possíveis dúvidas

**Comment by exageraldo** [comment]
Seja bem vindo @allythy !

**Comment by anapaulagomes** [comment]
Oi, @allythy! Ainda interessado nessa issue?

**Comment by gabrielcjr** [comment]
Oi pessoal! Eu fiz a substituição onde o método datetime.strptime era usado no projeto. Aqui a PR https://github.com/DadosAbertosDeFeira/maria-quiteria/pull/587
