### ISSUE TITLE
Remover jsonschema do requirements.txt

### ISSUE THREAD

**Issue by cuducos** [DadosAbertosDeFeira/maria-quiteria#411]
Adicionamos no #408 o `jsonchema==3.2.0` no `requirements.txt` pois:

* ele é uma dependência do `spidermon` (outro pacote)
* a versão 4 do `jsonschema` saiu há uns dias e quebrou o `spidermon`

Podemos retirar o `jsonschema==3.2.0` do nosso `requirements.txt` quando o `spidermon` resolver esse problema de incompatibilidade. Parte disso é remover a dependência de módulos não existentes no `jsonschema` versão 4 (https://github.com/scrapinghub/spidermon/issues/315) parte são outras possíveis incompatibilidades (https://github.com/scrapinghub/spidermon/pull/316#issuecomment-933029132).

Ou seja, provavelmente quando o `spidermon==1.16.0` for lançado, podemos retirar a dependência do `jsonschema==3.2.0`.

**Comment by anapaulagomes** [comment]
Feito.
