### ISSUE TITLE
Adicionar histórico de alterações aos models

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#61]
Em alguns casos, pode haver atualizações dos dados. Por exemplo: um vereador que estava ausente um dia pode ter sua falta justificada no outro. Para acompanhar essas situações, precisamos que os models salvem o histórico das atualizações.

É importante verificar também como fica o histórico em casos de criação ou atualizações em massa (`bulk_create`/`bulk_update`).

Alguns projetos que cumprem a tarefa:
* [django-simple-history](https://django-simple-history.readthedocs.io/en/latest/)
* [django-reversion](https://django-reversion.readthedocs.io/en/stable/)

**Comment by mayaradg** [comment]
Oiê :) Vou trabalhar nisso, ok?

**Comment by anapaulagomes** [comment]
Massa, @mayaradg! 🎉 Qualquer dúvida, só falar. Estamos também no [Telegram](https://t.me/dadosabertosdefeira).

**Comment by mayaradg** [comment]
Olá! Eu de novo :smile: Estou me ambientando nos modelos e trabalhando na issue e me ocorreu uma dúvida: Faz sentido a gente usar o histórico para todos os modelos ou para alguns não é necessário?

**Comment by anapaulagomes** [comment]
Boa pergunta, @mayaradg! 😅 Estava pensando aqui e acho que, no momento, podemos começar apenas com o [model de faltas dos vereadores](https://github.com/DadosAbertosDeFeira/maria-quiteria/blob/c53a581f61c8a50c50a0ce1c6a182a46153c29c6/datasets/models.py#L144). O que acha?
Outros como DO e atas não devem ser modificados depois de publicados. E outros como licitações sofrem modificações por conta de suas atualizações.

**Comment by mayaradg** [comment]
Concordo contigo, @anapaulagomes :smiley: abri um [PR](https://github.com/DadosAbertosDeFeira/maria-quiteria/pull/188) para adicionar a feature.
