### ISSUE TITLE
Adicionar um endpoint de opções disponíveis

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#612]
Esse endpoint vai servir para o nosso usuário visualizar as opções de busca no frontend. Devemos separar os endpoints por órgão e dar um nome amigável para eles. Exemplo:

- Prefeitura
    - Diário Oficial 
    - Licitações
    - …
- Câmara Municipal
    - Diário Oficial
    - Atas das sessões
    - …

Temos que retornar sempre o endpoint e o nome amigável de todas as fonte de dados disponíveis.

No caso do Diário Oficial temos o mesmo endpoint com filtro para o tipo diferente de poder (executivo ou legislativo).

**Comment by anapaulagomes** [comment]
Vê o que acha @matheusrocha89. Se tiver algum exemplo de endpoint que faça isso e seja público, manda pra nós.

**Comment by matheusrocha89** [comment]
Uma pergunta @anapaulagomes cada opção dessa aponta para um endpoint diferente, ou um serviço diferente que temos correto? Não temos um ponto único de busca onde usamos cada opção apenas como filtro

**Comment by anapaulagomes** [comment]
Não, não temos. Normalmente cada base tem seu endpoint, exceto por arquivos e diário oficial. Os arquivos são relacionados as bases de dados, então poderíamos implementar buscas relacionadas também (exemplo: a partir do endpoint de licitação buscar nos arquivos das licitações apenas).

**Comment by matheusrocha89** [comment]
Entendi. Era só para tirar uma dúvida mesmo.

**Comment by sheory** [comment]
Vou pegar essa issue. Por enquanto ainda estou analisando as possibilidades. Assim que tiver algo mais conclusivo vou escrevendo aqui. 
@anapaulagomes o front precisa receber tanto as opcoes como o link da rota que traz os dados para o caso de ser clicavel? Ou realmente seria so algo estatico com as fontes de dados disponiveis?

**Comment by anapaulagomes** [comment]
Agora que eu vi que eu escrevi uma resposta e não envie. Foi mal, @sheory!

Então, o front vai criar um dropdown pra os usuários com os nomes amigáveis das bases de dados (seguindo os grupos da descrição da issue). Pra poder fazer a busca a partir do que o usuário escolher, o front vai precisar também do link para os endpoints.

Depois vamos precisar entender como adicionar quais opções de filtros estão disponíveis em cada endpoint mas vamos começar pequeno.

**Comment by sheory** [comment]
Beleza! Não entendi como daria pra isso ser feito de forma dinâmica. Já que precisa além dos links, os nomes amigáveis. Para cada link deve ter um nome amigável, como isso pode ser feito de maneira dinâmica? Só pensei em algo estatístico até agora, onde teria uma rota pra cada órgão e estaticamente teria algo tipo:
Prefeitura: {
     Diário Oficial: path,
     Licitações: path
}
Você acha que dá pra fazer algo dinâmico pegando as rotas e os nomes amigáveis ao mesmo tempo? @anapaulagomes

**Comment by anapaulagomes** [comment]
Pensei melhor e, pela quantidade de endpoints, não vale a pena uma implementação dinâmica por agora. Podemos simplesmente ter em um dicionário mesmo. Podemos simplesmente retornar um dicionário com as opções, como:

```
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView


class FrontendEndpoint(APIView):
    renderer_classes = [JSONRenderer]
    AVAILABLE_ENDPOINTS_BY_PUBLIC_AGENCY = {
        "city-hall": {
            "public_agency": "Prefeitura",
            "endpoints": [
                {
                    "friendly_name": "Diário Oficial - Executivo",
                    "endpoint": "api/gazettes/?power=executive",
                },
                {
                    "friendly_name": "Licitações",
                    "endpoint": "api/city-hall/bids/",
                },
            ]
        },
        "city-council": {
            "public_agency": "Câmara Municipal",
            "endpoints": [
                {
                    "friendly_name": "Diário Oficial - Legislativo",
                    "endpoint": "api/gazettes/?power=legislative",
                },
                {
                    "friendly_name": "Atas das sessões",
                    "endpoint": "api/city-council/minute/",
                },
                {
                    "friendly_name": "Lista de presença dos vereadores",
                    "endpoint": "api/city-council/attendance-list/",
                }
            ]
        }
    }

    def get(self, request, format=None):
        return Response(AVAILABLE_ENDPOINTS_BY_PUBLIC_AGENCY)
```

Não testei, tá? É só um rascunho e não tem todas as opções. O que você acha, @sheory?

**Comment by sheory** [comment]
Acho que faz total sentido, hj vou começar a implementar por aq.
