### ISSUE TITLE
Criar um django-admin público

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#65]
Por enquanto não temos previsão para ter um frontend e seria legal já disponibilizar os dados que temos e deixá-los disponíveis para as pessoas buscarem, assim como o Serenata fez com o [Jarbas](https://jarbas.serenata.ai/dashboard/).

**Comment by cuducos** [comment]
Ficaria feliz em assumir essa _issue_. Eu fiz isso para o Jarbas da Serenata já pensando em uma _aplicação Django_ desacoplada do Jarbas, para facilitar o reaproveitamento de código.

Só nunca tive tempo e motivação para transformar o módulo [`public_admin`](https://github.com/okfn-brasil/serenata-de-amor/tree/master/jarbas/public_admin) em um instalável via `pip`.

Se eu fizer isso durante semana é um bom _timing_?

**Comment by anaschwendler** [comment]
Alô, eu quero me juntar a essa issue!

**Comment by anaschwendler** [comment]
Alô @cuducos vamos nos falar essa semana que eu tento fazer o que tu tá propondo se tu não tem tanto tempo livre, eu posso tentar ajudar e tu me guia :)

**Comment by cuducos** [comment]
Boa, @anaschwendler!

Separei o código aqui num repo, mais tarde subo para o GitHub. Aí tu me ajuda a testar e a aparar as arestas, pode ser?

**Comment by cuducos** [comment]
Pronto, comecei o rascunho: [Dajngo Public Admin](https://github.com/cuducos/django-public-admin).

**Comment by anaschwendler** [comment]
@cuducos eu preciso ter um momento hoensto:

que saudade dos teus typos <3

Vão ser bons tempos!

**Comment by cuducos** [comment]
Obriagdo, @anaschwendler :purple_heart: Nós!
