### ISSUE TITLE
Busca lenta no django-admin

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#66]
Antes de a gente _botar o bloco na rua_ com #65, precisamos resolver um problema importante de performance no `django-admin`. O número de registros não é um problema. O problema é que a busca checa arquivos muito grandes e ainda não temos uma busca, tipo _full text search_, pra aliviar a carga. A busca está lenta, especialmente, na página dos diários. Alguns diários, sozinhos, tem mais de 200 páginas.

Para reproduzir esse problema, você precisa:
* Rodar o comando `python manage.py crawl` com a variável de ambiente `FEATURE_FLAG__SAVE_GAZETTE=1`
* Rodar o servidor e, na página de diários, efetuar algumas buscas

Dica do @cuducos: https://github.com/okfn-brasil/serenata-de-amor/blob/master/jarbas/dashboard/admin/paginators.py

**Comment by jroquejr** [comment]
Quero pegar essa issue.

**Comment by cuducos** [comment]
Boa, @jroquejr! Conte comigo.

Na minha experiência com o Jarbas, duas ferramentas me ajudaram muito, mesmo localmente:

1. [Django Debug Toolbar](https://django-debug-toolbar.readthedocs.io/), principalmente naquela aba em que aparece o tempo de execução de cada _query_ no banco de dados
2. [pgHero](https://github.com/ankane/pghero) (fácil de rodar em produção também), para ver como podemos melhorar nosso modelo de dados (criar índices, por exemplo) e identificar gaargalos

Por fim, minha opinião sincera é o que a @anapaulagomes já adiantou: não temos um _full text search_, mas acho que deveríamos ter.

No Jarbas [consegui criar isso no PostgreSQL tudo pelo Django](https://github.com/okfn-brasil/serenata-de-amor/commit/9df9666d79f80f611c904bb0d739d5f0f8bdbce7) (o que facilita manuntenção e não deixa a cruva de entrada no projeto subir tanto), mas precisei utilizar funcionalidades específicas do PostgreSQL no ORM do Django.

Em outras palavras, se formos seguir o caminho do _full text search_, talvez o ponto negativo seria dependermos de PostgreSQL tanto local (desenvolvimento) quanto em produção.

**Comment by anapaulagomes** [comment]
> Em outras palavras, se formos seguir o caminho do full text search, talvez o ponto negativo seria dependermos de PostgreSQL tanto local (desenvolvimento) quanto em produção.

Acredito que estamos caminhando pra isso. Para o modelo de licitações, por exemplo, vamos ter que salvar uma lista de urls e seus conteúdos. A carga em cima de texto será grande. Acho que o _full text search_ seria ideal.

**Comment by anapaulagomes** [comment]
Me avisem se acharem que isso deveria estar em outra issue.

**Comment by jroquejr** [comment]
Obrigado @cuducos e @anapaulagomes  :heart_eyes: 

Me peguei exatamente nessa analise @cuducos, da necessidade de configurar os indices nos models, mas estava ponderando aqui o quão dependentes do postgres vamos ficar. Se não for um problema seguir usando Postgres, creio que o _full text search_ deve ser mesmo a saída.

Sobre a dependência do postgres localmente, esse seria um efeito colateral direto. Mas creio que vamos precisar alinhar os ambientes mais cedo ou mais tarde mesmo.

Sobre as ferramentas, conhecia a debug toolbar de outros carnavais. Sempre salva a pele (seu "irmão" para o flask também). Estava usando ela para validar as queries. Não conhecia o pgHero. , mas já gostei da premissa dele.

**Comment by jroquejr** [comment]
> Me avisem se acharem que isso deveria estar em outra issue.

Acredito que a implementação inicial deve vir dessa issue mesmo.

**Comment by jroquejr** [comment]
Atualizando: estou trabalhando no full_text_search. Tive uns contratempos com a configuração local, mas já atualizei o PR #75 para ajudar :)
