### ISSUE TITLE
Criar uma página inicial

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#67]
Essa página inicial seria apenas para ter uma página inicial. :sweat_smile: Necessitaria de:

- [x] Uma página de apresentação do projeto (o que é, como entrar em contato)
- [x] Link para o _dashboard_ (#65)
- [x] Links para redes sociais: [instagram](instagram.com/dadosabertosdefeira/), [facebook](https://www.facebook.com/dadosabertosdefeira), [blog](https://medium.com/@dadosabertosdefeira), [github](https://github.com/DadosAbertosDeFeira)

Outros links estão disponíveis também no [linktree](https://linktr.ee/dadosabertosdefeira).

Além dos links fixos, um espaço para links temporários, como o relatório do COVID19 em Feira (https://datastudio.google.com/u/0/reporting/cd9d3ac4-299b-46b4-bdab-8e9c081f5071?s=s8-Q-jNGhZg) é necessário.

**Comment by matheuscas** [comment]
✋🏼🙃

**Comment by anapaulagomes** [comment]
🎉
