### ISSUE TITLE
Transformar parte Django em um módulo único

### ISSUE THREAD

**Issue by cuducos** [DadosAbertosDeFeira/maria-quiteria#71]
Hoje a aplicação Django está espalhada no Maria Quitéria: tanto os módulos `datasest` quanto `core` são parte do Django. Podemos ter um módulo `web` ou `backend` encapsulando isso tudo, como o Henrique descreve [aqui](https://github.com/okfn-brasil/jarbas/issues/28). Me candidato a fazer esse refactor, por sinal ; ) O que acham?

**Comment by jroquejr** [comment]
Isso é indicado pela documentação do django, inclusive:
https://docs.djangoproject.com/en/3.0/intro/reusable-apps/

**Comment by anapaulagomes** [comment]
Acho uma boa. Eu já tinha visto outros apps usando esse estilo mas nunca tinha lido as explicações por trás. Embora a MQ não seja o caso de uma app pra ser reutilizada, faz sentido ter a parte Django isolada, principalmente pq a tendência é que a raiz do projeto continue crescendo e faz bem deixar tudo organizado. :) Obrigada, gente. Toca a ficha, @cuducos!

**Comment by cuducos** [comment]
Massa!

Vou espear o _merge_ da #60 para evitar muitos conflitos (como vou mover uns arquivos de lugar, o Git vez ou outra se perde e fica chato resolver os conflitos).

De boa?

**Comment by anapaulagomes** [comment]
Ótimo! @cuducos

**Comment by anapaulagomes** [comment]
Ei, @cuducos! Ainda anima fazer esse refactor? Se não, tem sugestões do como?

**Comment by cuducos** [comment]
Animo sim! Mas estou no meio de uma mudança aqui. Pode ser daqui umas 2 ou 3 semanas?

**Comment by anapaulagomes** [comment]
Pode sim, claro! ❤️ @cuducos Boa sorte com a mudança!
