### ISSUE TITLE
Fazer backup dos arquivos

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#73]
Atualmente baixamos os arquivos localmente, extraímos as informações e depois deletamos (caso a variável `KEEP_FILES` não esteja configurada). Seria interessante jogar esses arquivos para um S3 ou algo assim.

**Comment by cuducos** [comment]
Só para entender: hoje temos a variável `KEEP_FILES` (ou algo assim) que resolveria isso locamente. O que precisamos é uma alternativa para produção, como jogar os arquivos para um Spaces ou S3, por exemplo?

**Comment by anapaulagomes** [comment]
Perfeito, isso mesmo, @cuducos.
