### ISSUE TITLE
Alternativa para CI

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#76]
Gitlab não roda merge requests de repositórios externos:

> Pipelines for merge requests are incompatible with CI/CD for external repositories.

https://docs.gitlab.com/ee/ci/merge_request_pipelines/

Algumas alternativas:

* GitHub Actions
* Azure pipelines

Travis seria a Minha escolha número um mas, infelizmente, passou a limitar o número de builds gratuitos.

**Comment by cuducos** [comment]
+1 para GitHub Actions (motivo: simplicidade, seria uma plataforma a menos para a gente se preocupar).

**Comment by jroquejr** [comment]
+1 pro GitHub Actions também. Tenho usado nos meus projetos de teste e tem sido bem satisfatório. Curva de aprendizado foi mínima e bem, mais integrado ao GitHub, impossível.

**Comment by anapaulagomes** [comment]
No ano passado ainda estava em beta quando eu tentei rodar o GA com Postgres. Acho que por isso que eu não fui com ele logo de cara. Pelo que vi, muito já foi resolvido. Vamos tentar. :)
