### ISSUE TITLE
Coletar notícias da câmara de vereadores

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#8]
Endereço: https://www.feiradesantana.ba.leg.br/noticias.php

**Comment by joanasouza** [comment]
@anapaulagomes vou trabalhar nisso, ok?

**Comment by anapaulagomes** [comment]
Valeu demais, @joanasouza!

**Comment by anapaulagomes** [comment]
Oi, @joanasouza! Estamos organizando o repositório para o Hacktoberfest e checando as issues. Você está trabalhando nessa aqui?
