### ISSUE TITLE
Extrair arquivos para um único model

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#92]
Muitos models tem arquivos (suas URLs e conteúdos). Alguns deles passarão a ter uma lista de arquivo (como licitações). Estava pensando em eliminar a repetição e deixar os arquivos em um único model conectado por objetos genéricos. Algo mais ou menos assim:

```
class File(models.Model):
    file_url = models.URLField(null=True, blank=True)
    file_content = models.TextField(null=True, blank=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
```

Essa mudança facilitaria também em uma busca global de arquivos (#23). Uma outra vantagem seria a criação dos índices para a FTS em um lugar só (#80).

O que acham?

**Comment by cuducos** [comment]
Acho uma ótima ideia!

**Comment by jroquejr** [comment]
Boa ideia @anapaulagomes !!!

**Comment by jroquejr** [comment]
Posso aproveitar o que aprendi na #80 e pegar essa aqui :)

**Comment by anapaulagomes** [comment]
Por mim, tudo bem,@jroquejr! :tada:

**Comment by jroquejr** [comment]
Primeiramente: desculpem a demora. Saiu tudo do controle :(


Sobre a issue, pensei no seguinte:

* Vi que não usamos o conteúdo dos arquivos efetivamente, principalmente agora que estamos criando campos para vetor de busca. Tendo isso em mente, minha ideia é inicialmente parar de guardar o conteúdo dos arquivos dentro do banco de dados. Principalmente em formato de texto puro como está sendo salvo hoje.
Podemos usar o tipo File e armazenar em disco (no banco apenas uma referência). Isso abre uma gama de opções para escalar o armazenamento e funções de backup.

* Seguindo o modelo sugerido, salvariamos o search_vector no banco.

* Sobre a busca unificada, esse modelo resolve apenas a busca por conteúdo dentro dos arquivos, mas não outras chaves como datas, titulos ou urls. 
Podemos usar algumas alternativas existentes: https://github.com/etianen/django-watson

**Comment by anapaulagomes** [comment]
Sem problemas, @jroquejr! :tulip: Valeu por ter postado as suas ideias. Sobre elas:

* O conteúdo dos arquivos são usados nas buscas do `admin` e são um dos motivos fortes pelos quais essa busca existe (nos portais da transparência do município não é possível buscar pelo conteúdo, então muita informação fica escondida); a ideia é que as pessoas busquem e possam visualizar o conteúdo na página de detalhes. No PR #101 estou fazendo _upload_ dos arquivos para o S3 - essa seria nossa estratégia de _backup_ por hora (#73).
* :heavy_check_mark: 
* Você tem razão sobre isso. No meu último trabalho, usávamos o `django-watson`. Embora eu não tenha feito nada da implementação, posso dizer que, pelo menos para os usuários, funcionava super bem.

Importante dizer que esse _refactoring_ é bem importante para múltiplos arquivos por registro. As licitações, por exemplo, podem abrigar vários.
